# Generated by Django 5.2.9 on 2026-04-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "预约",
                "verbose_name_plural": "预约",
            },
        ),
        migrations.AlterModelOptions(
            name="appointmentrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "预约请求",
                "verbose_name_plural": "预约请求",
            },
        ),
        migrations.AlterModelOptions(
            name="appointmentreschedulehistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "改约记录",
                "verbose_name_plural": "改约记录",
            },
        ),
        migrations.AlterModelOptions(
            name="capacitystate",
            options={"verbose_name": "容量状态", "verbose_name_plural": "容量状态"},
        ),
        migrations.AlterModelOptions(
            name="config",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
            },
        ),
        migrations.AlterModelOptions(
            name="dayoff",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "休息日",
                "verbose_name_plural": "休息日",
            },
        ),
        migrations.AlterModelOptions(
            name="emailverificationcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "邮箱验证码",
                "verbose_name_plural": "邮箱验证码",
            },
        ),
        migrations.AlterModelOptions(
            name="passwordresettoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "密码重置令牌",
                "verbose_name_plural": "密码重置令牌",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentinfo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "支付信息",
                "verbose_name_plural": "支付信息",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["name"],
                "verbose_name": "服务",
                "verbose_name_plural": "服务",
            },
        ),
        migrations.AlterModelOptions(
            name="staffmember",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "verbose_name": "店员",
                "verbose_name_plural": "店员",
            },
        ),
        migrations.AlterModelOptions(
            name="workinghours",
            options={
                "ordering": ["day_of_week", "start_time"],
                "verbose_name": "营业时间",
                "verbose_name_plural": "营业时间",
            },
        ),
    ]
