# Generated by Django 5.2.9 on 2026-04-28 10:49

import appointment.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="allow_rescheduling",
            field=models.BooleanField(
                default=False,
                help_text="是否允许该服务的预约进行改约。",
                verbose_name="允许改约",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="background_color",
            field=models.CharField(
                blank=True,
                default=appointment.models.generate_rgb_color,
                max_length=50,
                null=True,
                verbose_name="背景颜色",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="service",
            name="currency",
            field=models.CharField(
                default="USD",
                max_length=3,
                validators=[
                    django.core.validators.MaxLengthValidator(3),
                    django.core.validators.MinLengthValidator(3),
                ],
                verbose_name="币种",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="service",
            name="down_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="定金",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.DurationField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=1)
                    )
                ],
                verbose_name="时长",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/", verbose_name="图像"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="价格",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="reschedule_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="该服务允许改约的最大次数。",
                verbose_name="改约次数上限",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="service",
            name="use_service_duration_as_slot",
            field=models.BooleanField(
                default=True,
                help_text="启用后，系统检查可预约时间时会使用该服务的实际时长，避免服务时长超过默认时间段时发生重叠。仅当系统配置中的“默认使用服务时长”关闭时，此设置才会生效。",
                verbose_name="使用服务时长作为时间段",
            ),
        ),
    ]
