# Generated by Django 5.2.9 on 2026-04-28 10:54

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_service_allow_rescheduling_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="additional_info",
            field=models.TextField(
                blank=True,
                help_text="客户希望补充说明的其他信息。",
                null=True,
                verbose_name="附加信息",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="可填写城市、区域或简要地址，不必过于详细。",
                max_length=255,
                null=True,
                verbose_name="地址",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="amount_to_pay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="该预约需要支付的金额。若为 0，表示免费或已经支付。",
                max_digits=10,
                null=True,
                verbose_name="应付金额",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_request",
            field=models.OneToOneField(
                help_text="客户提交的预约请求。",
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointmentrequest",
                verbose_name="预约请求",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                help_text="提交该预约请求的用户。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="entered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="客户被允许入场的时间。",
                null=True,
                verbose_name="入场时间",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="id_request",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="请求编号"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="left_at",
            field=models.DateTimeField(
                blank=True,
                help_text="客户离场并释放名额的时间。",
                null=True,
                verbose_name="离场时间",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(
                default=False, help_text="该预约是否已经付款。", verbose_name="已支付"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="电话号码"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "已预约"),
                    ("entered", "已入场"),
                    ("finished", "已离场"),
                    ("cancelled", "已取消"),
                ],
                default="booked",
                help_text="该预约当前的入场生命周期状态。",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="want_reminder",
            field=models.BooleanField(
                default=False,
                help_text="客户是否希望收到预约提醒。",
                verbose_name="需要提醒",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="date",
            field=models.DateField(help_text="预约请求的日期。", verbose_name="日期"),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="end_time",
            field=models.TimeField(
                help_text="预约请求的结束时间。", verbose_name="结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="id_request",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="请求编号"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="payment_type",
            field=models.CharField(
                choices=[("full", "全额支付"), ("down", "支付定金")],
                default="full",
                max_length=4,
                verbose_name="支付类型",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="reschedule_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="该预约已经改约的次数。", verbose_name="改约次数"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.service",
                verbose_name="服务",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="staff_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointment.staffmember",
                verbose_name="店员",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="start_time",
            field=models.TimeField(
                help_text="预约请求的开始时间。", verbose_name="开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="appointment_request",
            field=models.ForeignKey(
                help_text="客户提交的预约请求。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reschedule_histories",
                to="appointment.appointmentrequest",
                verbose_name="预约请求",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="该改约记录创建的日期和时间。",
                verbose_name="创建时间",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="date",
            field=models.DateField(help_text="改约前的预约日期。", verbose_name="日期"),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="end_time",
            field=models.TimeField(
                help_text="改约前的预约结束时间。", verbose_name="结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="id_request",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="请求编号"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="reason_for_rescheduling",
            field=models.TextField(
                blank=True,
                help_text="本次改约的原因。",
                null=True,
                verbose_name="改约原因",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="reschedule_status",
            field=models.CharField(
                choices=[("pending", "待确认"), ("confirmed", "已确认")],
                default="pending",
                help_text="本次改约操作的当前状态。",
                max_length=10,
                verbose_name="改约状态",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="staff_member",
            field=models.ForeignKey(
                help_text="改约前负责该预约的店员。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointment.staffmember",
                verbose_name="店员",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="start_time",
            field=models.TimeField(
                help_text="改约前的预约开始时间。", verbose_name="开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreschedulehistory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="该改约记录最后更新或确认的日期和时间。",
                verbose_name="更新时间",
            ),
        ),
        migrations.AlterField(
            model_name="capacitystate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="capacitystate",
            name="current_count",
            field=models.PositiveIntegerField(default=0, verbose_name="当前在场人数"),
        ),
        migrations.AlterField(
            model_name="capacitystate",
            name="max_capacity",
            field=models.PositiveIntegerField(default=50, verbose_name="最大容量"),
        ),
        migrations.AlterField(
            model_name="capacitystate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="config",
            name="allow_staff_change_on_reschedule",
            field=models.BooleanField(
                default=True,
                help_text="客户改约时是否允许更换负责该预约的店员。",
                verbose_name="改约时允许更换店员",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="app_offered_by_label",
            field=models.CharField(
                default="服务人员",
                help_text="预约页面中用于展示服务人员的标签文字。",
                max_length=255,
                verbose_name="服务人员标签",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="appointment_buffer_time",
            field=models.FloatField(
                help_text="从当前时间到当天第一个可预约时间段之间的缓冲时间，不影响明天及之后的预约。",
                null=True,
                verbose_name="预约缓冲时间",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="config",
            name="default_reschedule_limit",
            field=models.PositiveIntegerField(
                default=3,
                help_text="所有服务默认允许改约的最大次数。",
                verbose_name="默认改约次数上限",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="default_to_service_duration",
            field=models.BooleanField(
                default=True,
                help_text="启用后，所有服务在检查可预约时间时都会自动使用各自的服务时长，避免长服务发生时间重叠。关闭后，将使用每个服务自己的“使用服务时长作为时间段”设置。",
                verbose_name="默认使用服务时长",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="finish_time",
            field=models.TimeField(
                help_text="门店结束营业的时间。", null=True, verbose_name="结束营业时间"
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="lead_time",
            field=models.TimeField(
                help_text="门店开始营业的时间。", null=True, verbose_name="开始营业时间"
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="slot_duration",
            field=models.PositiveIntegerField(
                help_text="预约时间段的最小间隔，单位为分钟，建议填写 30。",
                null=True,
                verbose_name="时间段间隔",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="slot_gap_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="两个预约之间需要预留的休息时间，单位为分钟。除非店员单独配置，否则该设置应用于所有店员。",
                null=True,
                verbose_name="预约间隔时间",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="config",
            name="website_name",
            field=models.CharField(
                default="",
                help_text="当前预约网站显示的名称。",
                max_length=255,
                verbose_name="网站名称",
            ),
        ),
        migrations.AlterField(
            model_name="dayoff",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="dayoff",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="描述"
            ),
        ),
        migrations.AlterField(
            model_name="dayoff",
            name="end_date",
            field=models.DateField(verbose_name="结束日期"),
        ),
        migrations.AlterField(
            model_name="dayoff",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.staffmember",
                verbose_name="店员",
            ),
        ),
        migrations.AlterField(
            model_name="dayoff",
            name="start_date",
            field=models.DateField(verbose_name="开始日期"),
        ),
        migrations.AlterField(
            model_name="dayoff",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="code",
            field=models.CharField(
                help_text="发送到用户邮箱的验证码。",
                max_length=6,
                verbose_name="验证码",
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(verbose_name="过期时间"),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "有效"),
                    ("verified", "已验证"),
                    ("invalidated", "已失效"),
                ],
                default="active",
                max_length=11,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="令牌"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="paymentinfo",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointment",
                verbose_name="预约",
            ),
        ),
        migrations.AlterField(
            model_name="paymentinfo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="paymentinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="appointment_buffer_time",
            field=models.FloatField(
                blank=True,
                help_text="从当前时间到当天第一个可预约时间段之间的缓冲时间，单位为分钟，不影响明天及之后的预约。",
                null=True,
                verbose_name="预约缓冲时间",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="finish_time",
            field=models.TimeField(
                blank=True,
                help_text="该店员结束工作的时间。",
                null=True,
                verbose_name="结束营业时间",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="lead_time",
            field=models.TimeField(
                blank=True,
                help_text="该店员开始工作的时间。",
                null=True,
                verbose_name="开始营业时间",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="services_offered",
            field=models.ManyToManyField(
                help_text="该店员可以提供的服务。",
                to="appointment.service",
                verbose_name="提供的服务",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="slot_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="预约时间段的最小间隔，单位为分钟，建议填写 30。",
                null=True,
                verbose_name="时间段间隔",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="slot_gap_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="两个预约之间需要预留的休息时间，单位为分钟。该设置会覆盖全局系统配置。",
                null=True,
                verbose_name="预约间隔时间",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="work_on_saturday",
            field=models.BooleanField(
                default=False,
                help_text="该店员是否在星期六工作。",
                verbose_name="星期六工作",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="work_on_sunday",
            field=models.BooleanField(
                default=False,
                help_text="该店员是否在星期日工作。",
                verbose_name="星期日工作",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="day_of_week",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "星期日"),
                    (1, "星期一"),
                    (2, "星期二"),
                    (3, "星期三"),
                    (4, "星期四"),
                    (5, "星期五"),
                    (6, "星期六"),
                ],
                verbose_name="星期",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="end_time",
            field=models.TimeField(verbose_name="结束时间"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.staffmember",
                verbose_name="店员",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="start_time",
            field=models.TimeField(verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
